//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWit.Demo.WitEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutWit.Demo.WitEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WitEngine.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WitEngine Job File, *.job|*.job.
        /// </summary>
        internal static string LoadJobFiIter {
            get {
                return ResourceManager.GetString("LoadJobFiIter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ssss.
        /// </summary>
        internal static string ssss {
            get {
                return ResourceManager.GetString("ssss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Syntax name=&quot;JobEditorSyntax&quot;&gt;
        ///	&lt;HighlightRuleWords name=&quot;operators&quot;&gt;
        ///		&lt;Words&gt;
        ///			Job
        ///		&lt;/Words&gt;
        ///		&lt;IgnoreCase&gt;false&lt;/IgnoreCase&gt;
        ///		&lt;Foreground&gt;#3800FF&lt;/Foreground&gt;
        ///		&lt;FontWeight&gt;Bold&lt;/FontWeight&gt;
        ///		&lt;FontStyle&gt;Normal&lt;/FontStyle&gt;
        ///	&lt;/HighlightRuleWords&gt;
        ///	
        ///	&lt;HighlightRuleExpression name=&quot;Numbers&quot;&gt;
        ///    &lt;Expression&gt;\b([0-9]+)\b&lt;/Expression&gt;
        ///    &lt;IgnoreCase&gt;true&lt;/IgnoreCase&gt;
        ///    &lt;Foreground&gt;#F68A1B&lt;/Foreground&gt;
        ///    &lt;FontWeight&gt;Normal&lt;/FontWeight&gt;
        ///    &lt;FontStyle&gt;Normal&lt;/F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
