//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutWit.Controller.Special.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutWit.Controller.Special.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiOperatorsCancelled.
        /// </summary>
        internal static string MultiOperatorsCancelled {
            get {
                return ResourceManager.GetString("MultiOperatorsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiOperatorsCompleted.
        /// </summary>
        internal static string MultiOperatorsCompleted {
            get {
                return ResourceManager.GetString("MultiOperatorsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiOperatorsFailed.
        /// </summary>
        internal static string MultiOperatorsFailed {
            get {
                return ResourceManager.GetString("MultiOperatorsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiOperatorsStarted.
        /// </summary>
        internal static string MultiOperatorsStarted {
            get {
                return ResourceManager.GetString("MultiOperatorsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiOperatorsTimeout.
        /// </summary>
        internal static string MultiOperatorsTimeout {
            get {
                return ResourceManager.GetString("MultiOperatorsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialConcatStringDescription.
        /// </summary>
        internal static string SpecialConcatStringDescription {
            get {
                return ResourceManager.GetString("SpecialConcatStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialConcatStringErrorMessage.
        /// </summary>
        internal static string SpecialConcatStringErrorMessage {
            get {
                return ResourceManager.GetString("SpecialConcatStringErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialCopyDescription.
        /// </summary>
        internal static string SpecialCopyDescription {
            get {
                return ResourceManager.GetString("SpecialCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialCopyErrorMessage.
        /// </summary>
        internal static string SpecialCopyErrorMessage {
            get {
                return ResourceManager.GetString("SpecialCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialDelayedDescription.
        /// </summary>
        internal static string SpecialDelayedDescription {
            get {
                return ResourceManager.GetString("SpecialDelayedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialLoopDescription.
        /// </summary>
        internal static string SpecialLoopDescription {
            get {
                return ResourceManager.GetString("SpecialLoopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialLoopIterationStarted.
        /// </summary>
        internal static string SpecialLoopIterationStarted {
            get {
                return ResourceManager.GetString("SpecialLoopIterationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialParallelDescription.
        /// </summary>
        internal static string SpecialParallelDescription {
            get {
                return ResourceManager.GetString("SpecialParallelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialPathDescription.
        /// </summary>
        internal static string SpecialPathDescription {
            get {
                return ResourceManager.GetString("SpecialPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialPathErrorMessage.
        /// </summary>
        internal static string SpecialPathErrorMessage {
            get {
                return ResourceManager.GetString("SpecialPathErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialPauseDescription.
        /// </summary>
        internal static string SpecialPauseDescription {
            get {
                return ResourceManager.GetString("SpecialPauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialPauseErrorMessage.
        /// </summary>
        internal static string SpecialPauseErrorMessage {
            get {
                return ResourceManager.GetString("SpecialPauseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialReturnDescription.
        /// </summary>
        internal static string SpecialReturnDescription {
            get {
                return ResourceManager.GetString("SpecialReturnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialReturnErrorMessage.
        /// </summary>
        internal static string SpecialReturnErrorMessage {
            get {
                return ResourceManager.GetString("SpecialReturnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialSequentialDescription.
        /// </summary>
        internal static string SpecialSequentialDescription {
            get {
                return ResourceManager.GetString("SpecialSequentialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialTestDescription.
        /// </summary>
        internal static string SpecialTestDescription {
            get {
                return ResourceManager.GetString("SpecialTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialTestErrorMessage.
        /// </summary>
        internal static string SpecialTestErrorMessage {
            get {
                return ResourceManager.GetString("SpecialTestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialTimerDescription.
        /// </summary>
        internal static string SpecialTimerDescription {
            get {
                return ResourceManager.GetString("SpecialTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialUniqueNameDescription.
        /// </summary>
        internal static string SpecialUniqueNameDescription {
            get {
                return ResourceManager.GetString("SpecialUniqueNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialUniqueNameErrorMessage.
        /// </summary>
        internal static string SpecialUniqueNameErrorMessage {
            get {
                return ResourceManager.GetString("SpecialUniqueNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
